version: "3"
services:
  web:
    build:
      context: .
      dockerfile: app.dockerfile
    ports:
      - "0.0.0.0:80:80"
  db:
    image: postgres
    env_file:
      - database.env
    volumes:
    - database-data:/var/lib/postgresql/data

volumes:
  database-data: